INSERT INTO uf (id,cod,sigla,name) VALUES (11,11,'RO','Rondônia');
INSERT INTO uf (id,cod,sigla,name) VALUES (12,12,'AC','Acre');
INSERT INTO uf (id,cod,sigla,name) VALUES (13,13,'AM','Amazonas');
INSERT INTO uf (id,cod,sigla,name) VALUES (14,14,'RR','Roraima');
INSERT INTO uf (id,cod,sigla,name) VALUES (15,15,'PA','Pará');
INSERT INTO uf (id,cod,sigla,name) VALUES (16,16,'AP','Amapá');
INSERT INTO uf (id,cod,sigla,name) VALUES (17,17,'TO','Tocantins');
INSERT INTO uf (id,cod,sigla,name) VALUES (21,21,'MA','Maranhão');
INSERT INTO uf (id,cod,sigla,name) VALUES (22,22,'PI','Piauí');
INSERT INTO uf (id,cod,sigla,name) VALUES (23,23,'CE','Ceará');
INSERT INTO uf (id,cod,sigla,name) VALUES (24,24,'RN','Rio Grande do Norte');
INSERT INTO uf (id,cod,sigla,name) VALUES (25,25,'PB','Paraíba');
INSERT INTO uf (id,cod,sigla,name) VALUES (26,26,'PE','Pernambuco');
INSERT INTO uf (id,cod,sigla,name) VALUES (27,27,'AL','Alagoas');
INSERT INTO uf (id,cod,sigla,name) VALUES (28,28,'SE','Sergipe');
INSERT INTO uf (id,cod,sigla,name) VALUES (29,29,'BA','Bahia');
INSERT INTO uf (id,cod,sigla,name) VALUES (31,31,'MG','Minas Gerais');
INSERT INTO uf (id,cod,sigla,name) VALUES (32,32,'ES','Espírito Santo');
INSERT INTO uf (id,cod,sigla,name) VALUES (33,33,'RJ','Rio de Janeiro');
INSERT INTO uf (id,cod,sigla,name) VALUES (35,35,'SP','São Paulo');
INSERT INTO uf (id,cod,sigla,name) VALUES (41,41,'PR','Paraná');
INSERT INTO uf (id,cod,sigla,name) VALUES (42,42,'SC','Santa Catarina');
INSERT INTO uf (id,cod,sigla,name) VALUES (43,43,'RS','Rio Grande do Sul');
INSERT INTO uf (id,cod,sigla,name) VALUES (50,50,'MS','Mato Grosso do Sul');
INSERT INTO uf (id,cod,sigla,name) VALUES (51,51,'MT','Mato Grosso');
INSERT INTO uf (id,cod,sigla,name) VALUES (52,52,'GO','Goiás');
INSERT INTO uf (id,cod,sigla,name) VALUES (53,53,'DF','Distrito Federal');
